title: 計算研究会
description: >- # this means to ignore newlines until "baseurl:"
  計算研究会のホームページです。私たちは三重大学を主軸に活動する「計算」の研究会です。
baseurl: ""
url: "https://www.calc.mie.jp"

twitter_username: calc_mie
github_username: calc-mie

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude: ["_site"]
