FROM ruby:3.3-alpine3.19

ENV TZ Asia/Tokyo

RUN apk --no-cache add \
    build-base git tzdata vim curl && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    rm -rf /var/cache/apk/*

RUN git config --global core.filemode false && \
    git config --global core.autocrlf input && \
    git config --global --add safe.directory /workspace

RUN gem install bundler

COPY Gemfile /tmp/
COPY Gemfile.lock /tmp/
WORKDIR /tmp
RUN bundler install
