FROM rockstorm/jekyll:pages-v228-minimal

ENV PAGES_REPO_NWO calc-mie/pages-calc-mie-jp
ENV TZ Asia/Tokyo

RUN apk --no-cache add \
    g++ \
    ca-certificates \
    curl \
    file \
    git \
    make \
    tzdata \
    vim && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    rm -rf /var/cache/apk/*

RUN git config --global core.filemode false && \
    git config --global core.autocrlf input && \
    git config --global --add safe.directory /workspace

RUN gem update bundler
